# Markdownlint configuration
# See: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

default: true

# MD013: Line length
MD013:
  line_length: 120
  heading_line_length: 120
  code_block_line_length: 120
  code_blocks: true
  tables: true
  headings: true
  strict: false

# MD024: Multiple headings with the same content
MD024:
  siblings_only: true

# MD033: Inline HTML
MD033:
  allowed_elements:
    - br
    - sub
    - sup

# MD041: First line in file should be a top level heading
MD041: false

# MD046: Code block style
MD046:
  style: fenced
